/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Docusaurus",
  "tagline": "Build optimized websites quickly, focus on your content",
  "organizationName": "facebook",
  "projectName": "docusaurus",
  "baseUrl": "/",
  "baseUrlIssueBanner": true,
  "url": "https://docusaurus.io",
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true
    },
    "experimental_faster": {
      "swcJsLoader": true,
      "swcJsMinimizer": true,
      "swcHtmlMinimizer": true,
      "lightningCssMinimizer": true,
      "mdxCrossCompilerCache": true,
      "rspackBundler": true,
      "rspackPersistentCache": true,
      "ssgWorkerThreads": true
    },
    "experimental_storage": {
      "namespace": true,
      "type": "localStorage"
    },
    "experimental_router": "browser"
  },
  "trailingSlash": false,
  "stylesheets": [
    {
      "href": "/katex/katex.min.css",
      "type": "text/css"
    }
  ],
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en",
      "fr",
      "pt-BR",
      "ko",
      "zh-CN"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "markdown": {
    "format": "detect",
    "mermaid": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "remarkRehypeOptions": {
      "footnoteLabel": "Footnotes"
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "onBrokenLinks": "warn",
  "onBrokenAnchors": "warn",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/docusaurus.ico",
  "customFields": {
    "crashTest": false,
    "isDeployPreview": false,
    "description": "An optimized site generator in React. Docusaurus helps you to move fast and write content. Build documentation websites, blogs, marketing pages, and more."
  },
  "staticDirectories": [
    "static"
  ],
  "themes": [
    "live-codeblock"
  ],
  "plugins": [
    false,
    [
      "./src/plugins/changelog/index.ts",
      {
        "blogTitle": "Docusaurus changelog",
        "blogDescription": "Keep yourself up-to-date about new features in every release",
        "blogSidebarCount": "ALL",
        "blogSidebarTitle": "Changelog",
        "routeBasePath": "/changelog",
        "showReadingTime": false,
        "postsPerPage": 20,
        "archiveBasePath": null,
        "authorsMapPath": "authors.json",
        "feedOptions": {
          "type": "all",
          "title": "Docusaurus changelog",
          "description": "Keep yourself up-to-date about new features in every release",
          "copyright": "Copyright © 2025 Facebook, Inc.",
          "language": "en"
        },
        "onInlineAuthors": "warn"
      }
    ],
    [
      "ideal-image",
      {
        "quality": 70,
        "max": 1030,
        "min": 640,
        "steps": 2,
        "disableInDev": true
      }
    ],
    [
      "pwa",
      {
        "offlineModeActivationStrategies": [
          "appInstalled",
          "standalone",
          "queryString"
        ],
        "swCustom": "C:\\Users\\alexe\\Downloads\\docusaurus-main\\docusaurus-main\\website\\src\\sw.js",
        "pwaHead": [
          {
            "tagName": "link",
            "rel": "icon",
            "href": "img/docusaurus.png"
          },
          {
            "tagName": "link",
            "rel": "manifest",
            "href": "manifest.json"
          },
          {
            "tagName": "meta",
            "name": "theme-color",
            "content": "rgb(37, 194, 160)"
          },
          {
            "tagName": "meta",
            "name": "apple-mobile-web-app-capable",
            "content": "yes"
          },
          {
            "tagName": "meta",
            "name": "apple-mobile-web-app-status-bar-style",
            "content": "#000"
          },
          {
            "tagName": "link",
            "rel": "apple-touch-icon",
            "href": "img/docusaurus.png"
          },
          {
            "tagName": "link",
            "rel": "mask-icon",
            "href": "img/docusaurus.png",
            "color": "rgb(62, 204, 94)"
          },
          {
            "tagName": "meta",
            "name": "msapplication-TileImage",
            "content": "img/docusaurus.png"
          },
          {
            "tagName": "meta",
            "name": "msapplication-TileColor",
            "content": "#000"
          }
        ]
      }
    ],
    "@docusaurus/theme-mermaid",
    "./src/plugins/featureRequests/FeatureRequestsPlugin.js"
  ],
  "presets": [
    [
      "classic",
      {
        "debug": true,
        "docs": {
          "routeBasePath": "/",
          "path": "docs",
          "sidebarPath": "sidebars.ts",
          "admonitions": {
            "keywords": [
              "my-custom-admonition"
            ]
          },
          "showLastUpdateAuthor": false,
          "showLastUpdateTime": false,
          "remarkPlugins": [
            [
              null,
              {
                "sync": true
              }
            ],
            null,
            null
          ],
          "rehypePlugins": [
            null
          ],
          "disableVersioning": false,
          "lastVersion": "current",
          "onlyIncludeVersions": [
            "current"
          ],
          "versions": {
            "current": {
              "label": "PAW Docs v1.1 🚧"
            }
          }
        },
        "blog": {
          "path": "blog",
          "showLastUpdateAuthor": false,
          "showLastUpdateTime": false,
          "remarkPlugins": [
            null
          ],
          "postsPerPage": 5,
          "feedOptions": {
            "type": "all",
            "description": "Keep up to date with upcoming Docusaurus releases and articles by following our feed!",
            "copyright": "Copyright © 2025 Facebook, Inc.",
            "xslt": true
          },
          "blogTitle": "Docusaurus blog",
          "blogDescription": "Read blog posts about Docusaurus from the team",
          "blogSidebarCount": "ALL",
          "blogSidebarTitle": "All our posts",
          "onUntruncatedBlogPosts": "warn",
          "onInlineTags": "warn"
        },
        "pages": {
          "remarkPlugins": [
            null
          ],
          "showLastUpdateAuthor": false,
          "showLastUpdateTime": false
        },
        "theme": {
          "customCss": [
            "./src/css/custom.css"
          ]
        },
        "gtag": {
          "trackingID": [
            "G-E5CR2Q1NRE"
          ]
        },
        "sitemap": {
          "lastmod": "date",
          "priority": null,
          "changefreq": null
        },
        "svgr": {
          "svgrConfig": {}
        }
      }
    ]
  ],
  "themeConfig": {
    "liveCodeBlock": {
      "playgroundPosition": "bottom"
    },
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "announcementBar": {
      "id": "announcementBar-v1",
      "content": "👉️ <b><a target=\"_blank\" href=\"https://pawchain.net/blog/\">Keep up to date with the PAW Chain Blog</a> </b> 👈",
      "isCloseable": true
    },
    "prism": {
      "additionalLanguages": [
        "java",
        "latex",
        "haskell",
        "matlab",
        "php",
        "powershell",
        "bash",
        "diff",
        "json",
        "scss"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        },
        {
          "className": "code-block-error-line",
          "line": "This will error"
        }
      ],
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          },
          {
            "types": [
              "title"
            ],
            "style": {
              "color": "#0550AE",
              "fontWeight": "bold"
            }
          },
          {
            "types": [
              "parameter"
            ],
            "style": {
              "color": "#953800"
            }
          },
          {
            "types": [
              "boolean",
              "rule",
              "color",
              "number",
              "constant",
              "property"
            ],
            "style": {
              "color": "#005CC5"
            }
          },
          {
            "types": [
              "atrule",
              "tag"
            ],
            "style": {
              "color": "#22863A"
            }
          },
          {
            "types": [
              "script"
            ],
            "style": {
              "color": "#24292E"
            }
          },
          {
            "types": [
              "operator",
              "unit",
              "rule"
            ],
            "style": {
              "color": "#D73A49"
            }
          },
          {
            "types": [
              "font-matter",
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#C6105F"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "#116329"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "#0550AE"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "color": "#CF222E"
            }
          },
          {
            "types": [
              "function"
            ],
            "style": {
              "color": "#8250DF"
            }
          },
          {
            "types": [
              "selector"
            ],
            "style": {
              "color": "#6F42C1"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "#E36209"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "#6B6B6B"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#D4D4D4",
          "backgroundColor": "#212121"
        },
        "styles": [
          {
            "types": [
              "prolog"
            ],
            "style": {
              "color": "rgb(0, 0, 128)"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(106, 153, 85)"
            }
          },
          {
            "types": [
              "builtin",
              "changed",
              "keyword",
              "interpolation-punctuation"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "number",
              "inserted"
            ],
            "style": {
              "color": "rgb(181, 206, 168)"
            }
          },
          {
            "types": [
              "constant"
            ],
            "style": {
              "color": "rgb(100, 102, 149)"
            }
          },
          {
            "types": [
              "attr-name",
              "variable"
            ],
            "style": {
              "color": "rgb(156, 220, 254)"
            }
          },
          {
            "types": [
              "deleted",
              "string",
              "attr-value",
              "template-punctuation"
            ],
            "style": {
              "color": "rgb(206, 145, 120)"
            }
          },
          {
            "types": [
              "selector"
            ],
            "style": {
              "color": "rgb(215, 186, 125)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "rgb(212, 212, 212)"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "#808080"
            }
          },
          {
            "types": [
              "function"
            ],
            "style": {
              "color": "rgb(220, 220, 170)"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "char"
            ],
            "style": {
              "color": "rgb(209, 105, 105)"
            }
          },
          {
            "types": [
              "title"
            ],
            "style": {
              "color": "#569CD6",
              "fontWeight": "bold"
            }
          },
          {
            "types": [
              "property",
              "parameter"
            ],
            "style": {
              "color": "#9CDCFE"
            }
          },
          {
            "types": [
              "script"
            ],
            "style": {
              "color": "#D4D4D4"
            }
          },
          {
            "types": [
              "boolean",
              "arrow",
              "atrule",
              "tag"
            ],
            "style": {
              "color": "#569CD6"
            }
          },
          {
            "types": [
              "number",
              "color",
              "unit"
            ],
            "style": {
              "color": "#B5CEA8"
            }
          },
          {
            "types": [
              "font-matter"
            ],
            "style": {
              "color": "#CE9178"
            }
          },
          {
            "types": [
              "keyword",
              "rule"
            ],
            "style": {
              "color": "#C586C0"
            }
          },
          {
            "types": [
              "regex"
            ],
            "style": {
              "color": "#D16969"
            }
          },
          {
            "types": [
              "maybe-class-name"
            ],
            "style": {
              "color": "#4EC9B0"
            }
          },
          {
            "types": [
              "constant"
            ],
            "style": {
              "color": "#4FC1FF"
            }
          }
        ]
      }
    },
    "image": "img/docusaurus-social-card.jpg",
    "algolia": {
      "appId": "KIL8ZUEHIZ",
      "apiKey": "159c65d178f11644fa8289c2c7287170",
      "indexName": "pawchain_docs",
      "replaceSearchResultPathname": {
        "from": "^\\/docs\\/next\\/(.*)",
        "to": "/$1"
      },
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "navbar": {
      "hideOnScroll": true,
      "title": "Documentation",
      "logo": {
        "alt": "",
        "src": "img/PawChainLogo.svg",
        "srcDark": "img/docusaurus_keytar.svg",
        "width": 150,
        "height": 32
      },
      "items": [
        {
          "href": "https://t.me/pawecosystem",
          "position": "right",
          "className": "header-telegram-link",
          "aria-label": "Telegram"
        },
        {
          "href": "http://www.discord.gg/pawecosystem",
          "position": "right",
          "className": "header-discord-link",
          "aria-label": "Discord"
        },
        {
          "href": "https://www.reddit.com/r/PAWTechnology/?rdt=49180",
          "position": "right",
          "className": "header-reddit-link",
          "aria-label": "Reddit"
        },
        {
          "href": "https://x.com/pawchain",
          "position": "right",
          "className": "header-x-link",
          "aria-label": "X (Twitter)"
        }
      ]
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Get Started",
          "items": [
            {
              "label": "Set Up a PAW Wallet",
              "to": "/set-up-a-paw-wallet"
            },
            {
              "label": "How To Obtain $PAW",
              "to": "/how-to-obtain-paw"
            },
            {
              "label": "Connect to PAW Swap",
              "to": "/connecting-to-paw-swap"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Follow Us On X",
              "href": "https://x.com/pawchain"
            },
            {
              "label": "Join Our Discord",
              "href": "http://www.discord.gg/pawecosystem"
            },
            {
              "label": "Join Our Telegram",
              "href": "https://t.me/pawecosystem"
            },
            {
              "label": "Join Our Subreddit",
              "href": "https://www.reddit.com/r/PAWTechnology/?rdt=49180t"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Blog",
              "href": "https://pawchain.net/blog/"
            },
            {
              "label": "Contact",
              "href": "https://www.pawchain.net/about#Contact"
            },
            {
              "label": "CMC Community",
              "href": "https://coinmarketcap.com/community/profile/PawChain/"
            },
            {
              "label": "YouTube",
              "href": "https://www.youtube.com/@pawecosystem"
            }
          ]
        },
        {
          "title": "Legal",
          "className": "footer-column-legal",
          "items": [
            {
              "label": "Privacy",
              "className": "footer-item-privacy",
              "to": "/legal-and-compliance/privacy-policy"
            },
            {
              "label": "Terms",
              "to": "/legal-and-compliance/terms-of-use"
            },
            {
              "label": "Compliance and Disclosures",
              "to": "/legal-and-compliance/compliance-and-regulatory-disclosures"
            }
          ]
        }
      ],
      "logo": {
        "alt": "PAW Chain Logo",
        "src": "/img/docusaurus_keytar.svg",
        "href": "https://pawchain.net"
      },
      "copyright": "Copyright © 2025 PAW Chain."
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "mermaid": {
      "theme": {
        "dark": "dark",
        "light": "default"
      },
      "options": {}
    }
  },
  "onDuplicateRoutes": "warn",
  "scripts": [],
  "headTags": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
